### ISSUE TITLE
issues when trying to build

### ISSUE THREAD

**Issue by mph070770** [chintan1891/iOS-Alexa#1]
Hi,

I get 2 errors:

/Users/zzx/Desktop/IOS_Apps/iOS-Alexa-master/iOS Alexa/iOS Alexa-Bridging-Header.h:5:9: error: 'LoginWithAmazon/LoginWithAmazon.h' file not found
# import <LoginWithAmazon/LoginWithAmazon.h>

```
    ^
```

<unknown>:0: error: failed to import bridging header '/Users/zzx/Desktop/IOS_Apps/iOS-Alexa-master/iOS Alexa/iOS Alexa-Bridging-Header.h'

Can you help?

**Comment by chintan1891** [comment]
Can you please remove "LoginWithAmazon.framework" and add it again?
