### ISSUE TITLE
Login Action not working

### ISSUE THREAD

**Issue by vivekmpios** [chintan1891/iOS-Alexa#2]
I downloaded the project, and did setup everything as per you mentioned.
I am able to successfully fun the project on my simulator. But i when i click on Login  button nothing happens??

Thanks

**Comment by vivekmpios** [comment]
Do you think it might be because i was running it  on ios 10 or greater  ??

**Comment by chintan1891** [comment]
Can you please verify that you have followed all steps which i mentioned in to "README.md"
- Changes in "Config.swift"
- Changes in "LoginViewController.m"
- Changes in "Info.plist" for APIKey & URL Scheme

**Comment by vivekmpios** [comment]
Yes  i have.

I tried i to run it on simulator with ios 9.3. i was successfully able to run it.
Also the login action is taking me to amazon login page now.

Although i am getting this error when i try to login on Amazon page - "Safari cannot open the page because address is invalid". If you can help here (perhaps something with redirect url here, just guessing).

Also how were you able to archive this code. Error while archiving 
 "bitcode bundle could not be generated because $projDir//iOS-Alexa-master/iOS Alexa/LoginWithAmazon.framework/LoginWithAmazon(AIMobileLib.o)'  was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7"


I appreciate your quick response on that.
Thanks

**Comment by vivekmpios** [comment]
I was trying to Archive it because i just want to run it on actual device and i can't run it on a device on a Debug with earlier version of Xcode below 8 as they don't support disk image for a higher iOS version . And with higher version of Xcode 8 i don't want to end up facing and fixing all those code conversion errors, as  of now.

**Comment by chintan1891** [comment]
> I tried i to run it on simulator with ios 9.3. i was successfully able to run it.
> Also the login action is taking me to amazon login page now.
> 
> Although i am getting this error when i try to login on Amazon page - "Safari cannot open the page because address is invalid". If you can help here (perhaps something with redirect url here, just guessing).

**Solution: Please check if your bundleId (com.companyname.productname) is registered on AVS (Amazon Voice Service). And you are using same bundleId in URL Scheme & also you have updated APIKey in info.plist**

> Also how were you able to archive this code. Error while archiving 
>  "bitcode bundle could not be generated because $projDir//iOS-Alexa-master/iOS Alexa/LoginWithAmazon.framework/LoginWithAmazon(AIMobileLib.o)'  was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7"

**Solution: Disable Bitcode : http://stackoverflow.com/questions/31205133/how-to-enable-bitcode-in-xcode-7**

**Using Xcode 7 for iOS 10 device: http://bsn.io/code/reference/2016/08/26/installing-on-ios-10-with-xcode-7/**

In iOS 10, if you do not get voice response try in normal speaker (which we used while calling), not bottom speaker.

**Comment by vivekmpios** [comment]
Hey Thanks Man.

**Please check if your bundleId (com.companyname.productname) is registered on AVS (Amazon Voice Service). And you are using same bundleId in URL Scheme & also you have updated APIKey in info.plist**
here is a screenshot from my simulator. This comes once i login and accept terms and condition from amazon.
![screen shot 2016-12-12 at 8 37 56 pm](https://cloud.githubusercontent.com/assets/24523708/21104094/3e6cd102-c0ab-11e6-8598-54569fae1296.png)


Will definitely look into the other running on ios 10 from xcode 7, seems insightful to me.

Thanks.
Cheers

**Comment by vivekmpios** [comment]
Hey Chintan, 

Thanks man, you're the Master :)
There was some URL Scheme mistake.

I will definitely look into the link for - Using Xcode 7 for iOS 10 device. Seems insightful to me !!

**In iOS 10, if you do not get voice response try in normal speaker (which we used while calling), not bottom speaker.**
Here you can really change the category for AVAudioSession before playing the audio

.
.
.
**_let session = AVAudioSession.sharedInstance()
 try session.setCategory(AVAudioSessionCategoryPlayAndRecord,
                                                withOptions:AVAudioSessionCategoryOptions.DefaultToSpeaker)_**
just before..
 **self.player?.play()**



Thanks
